services:
  diamondcityradio-web:
    image: diamondcityradio
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diamondcityradio
    ports:
      - "11120:80"
    restart: unless-stopped
